# Generated by Django 3.1.3 on 2021-06-30 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arudl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('halaman', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Balaghoh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('halaman', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faroid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('halaman', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mantiq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('halaman', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Muin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('halaman', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nubzah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('halaman', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qorib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('halaman', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qowaid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('halaman', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Santri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('jk', models.CharField(blank=True, choices=[('laki-laki', 'laki-laki'), ('perempuan', 'perempuan')], max_length=20, null=True)),
                ('marhalah', models.CharField(blank=True, choices=[('Idadiyah', 'Idadiyah'), ('Mahad Aly', 'Mahad Aly'), ('Tamhidiyah', 'Tamhidiyah')], max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('halaman', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='strUsul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lafadz', models.CharField(blank=True, max_length=200, null=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True, null=True)),
                ('predikat', models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('A', 'A')], max_length=30, null=True)),
                ('halaman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appstor.usul')),
                ('nama', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appstor.santri')),
            ],
        ),
        migrations.CreateModel(
            name='strQowaid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lafadz', models.CharField(blank=True, max_length=200, null=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True, null=True)),
                ('predikat', models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('A', 'A')], max_length=30, null=True)),
                ('halaman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appstor.qowaid')),
                ('nama', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appstor.santri')),
            ],
        ),
        migrations.CreateModel(
            name='strQorib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lafadz', models.CharField(blank=True, max_length=200, null=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True, null=True)),
                ('predikat', models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('A', 'A')], max_length=30, null=True)),
                ('halaman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appstor.qorib')),
                ('nama', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appstor.santri')),
            ],
        ),
        migrations.CreateModel(
            name='strNubzah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lafadz', models.CharField(blank=True, max_length=200, null=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True, null=True)),
                ('predikat', models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('A', 'A')], max_length=30, null=True)),
                ('halaman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appstor.nubzah')),
                ('nama', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appstor.santri')),
            ],
        ),
        migrations.CreateModel(
            name='strMuin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lafadz', models.CharField(blank=True, max_length=200, null=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True, null=True)),
                ('predikat', models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('A', 'A')], max_length=30, null=True)),
                ('halaman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appstor.muin')),
                ('nama', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appstor.santri')),
            ],
        ),
        migrations.CreateModel(
            name='strMantiq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lafadz', models.CharField(blank=True, max_length=200, null=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True, null=True)),
                ('predikat', models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('A', 'A')], max_length=30, null=True)),
                ('halaman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appstor.mantiq')),
                ('nama', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appstor.santri')),
            ],
        ),
        migrations.CreateModel(
            name='strFaroid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lafadz', models.CharField(blank=True, max_length=200, null=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True, null=True)),
                ('predikat', models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('A', 'A')], max_length=30, null=True)),
                ('halaman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appstor.faroid')),
                ('nama', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appstor.santri')),
            ],
        ),
        migrations.CreateModel(
            name='strBalaghoh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lafadz', models.CharField(blank=True, max_length=200, null=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True, null=True)),
                ('predikat', models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('A', 'A')], max_length=30, null=True)),
                ('halaman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appstor.balaghoh')),
                ('nama', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appstor.santri')),
            ],
        ),
        migrations.CreateModel(
            name='strArudl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lafadz', models.CharField(blank=True, max_length=200, null=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True, null=True)),
                ('predikat', models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('A', 'A')], max_length=30, null=True)),
                ('halaman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appstor.arudl')),
                ('nama', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appstor.santri')),
            ],
        ),
    ]
