# Generated by Django 3.1.3 on 2021-06-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstor', '0002_auto_20210701_0628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arudl',
            old_name='halaman',
            new_name='halaman6',
        ),
        migrations.RenameField(
            model_name='balaghoh',
            old_name='halaman',
            new_name='halaman7',
        ),
        migrations.RenameField(
            model_name='faroid',
            old_name='halaman',
            new_name='halaman4',
        ),
        migrations.RenameField(
            model_name='mantiq',
            old_name='halaman',
            new_name='halaman5',
        ),
        migrations.RenameField(
            model_name='muin',
            old_name='halaman',
            new_name='halaman3',
        ),
        migrations.RenameField(
            model_name='nubzah',
            old_name='halaman',
            new_name='halaman1',
        ),
        migrations.RenameField(
            model_name='qowaid',
            old_name='halaman',
            new_name='halaman8',
        ),
        migrations.RenameField(
            model_name='usul',
            old_name='halaman',
            new_name='halaman9',
        ),
        migrations.RemoveField(
            model_name='qorib',
            name='halaman',
        ),
        migrations.AddField(
            model_name='qorib',
            name='halaman2',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='jk',
            field=models.CharField(blank=True, choices=[('perempuan', 'perempuan'), ('laki-laki', 'laki-laki')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='marhalah',
            field=models.CharField(blank=True, choices=[('Idadiyah', 'Idadiyah'), ('Mahad Aly', 'Mahad Aly'), ('Tamhidiyah', 'Tamhidiyah')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strarudl',
            name='predikat',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('A', 'A')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strbalaghoh',
            name='predikat',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('A', 'A')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strfaroid',
            name='predikat',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('A', 'A')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strmantiq',
            name='predikat',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('A', 'A')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strmuin',
            name='predikat',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('A', 'A')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strnubzah',
            name='predikat',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('A', 'A')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strqorib',
            name='predikat',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('A', 'A')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strqowaid',
            name='predikat',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('A', 'A')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strusul',
            name='predikat',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('A', 'A')], max_length=30, null=True),
        ),
    ]
