# Generated by Django 3.1.3 on 2021-06-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstor', '0004_auto_20210701_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arudl',
            name='halaman6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='balaghoh',
            name='halaman7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faroid',
            name='halaman4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mantiq',
            name='halaman5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='muin',
            name='halaman3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nubzah',
            name='halaman1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qorib',
            name='halaman2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qowaid',
            name='halaman8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='jk',
            field=models.CharField(blank=True, choices=[('perempuan', 'perempuan'), ('laki-laki', 'laki-laki')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='marhalah',
            field=models.CharField(blank=True, choices=[('Mahad Aly', 'Mahad Aly'), ('Tamhidiyah', 'Tamhidiyah'), ('Idadiyah', 'Idadiyah')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strarudl',
            name='predikat',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('A', 'A')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strbalaghoh',
            name='predikat',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('A', 'A')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strfaroid',
            name='predikat',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('A', 'A')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strmantiq',
            name='predikat',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('A', 'A')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strmuin',
            name='predikat',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('A', 'A')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strnubzah',
            name='predikat',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('A', 'A')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strqorib',
            name='predikat',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('A', 'A')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strqowaid',
            name='predikat',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('A', 'A')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strusul',
            name='predikat',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('A', 'A')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usul',
            name='halaman9',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
