# Generated by Django 3.1.3 on 2021-07-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstor', '0012_auto_20210701_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='santri',
            name='jk',
            field=models.CharField(blank=True, choices=[('laki-laki', 'laki-laki'), ('perempuan', 'perempuan')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='marhalah',
            field=models.CharField(blank=True, choices=[('Mahad Aly', 'Mahad Aly'), ('Idadiyah', 'Idadiyah'), ('Tamhidiyah', 'Tamhidiyah')], max_length=30, null=True),
        ),
    ]
