# Generated by Django 3.1.3 on 2021-07-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstor', '0070_auto_20210703_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juznubzah',
            name='juz',
            field=models.CharField(blank=True, choices=[('juz 2', 'juz 2'), ('juz 1', 'juz 1'), ('juz 5', 'juz 5'), ('juz 3', 'juz 3'), ('takmilah', 'takmilah'), ('juz 4', 'juz 4')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='jk',
            field=models.CharField(blank=True, choices=[('perempuan', 'perempuan'), ('laki-laki', 'laki-laki')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='marhalah',
            field=models.CharField(blank=True, choices=[('Tamhidiyah', 'Tamhidiyah'), ('Idadiyah', 'Idadiyah'), ('Mahad Aly', 'Mahad Aly')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='status',
            field=models.CharField(blank=True, choices=[('mahasiswa', 'mahasiswa'), ('siswa', 'siswa'), ('salaf', 'salaf')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='takhossus',
            field=models.CharField(blank=True, choices=[('faroid', 'faroid'), ('usul fiqh', 'usul fiqh'), ('arudl', 'arudl'), ('qowaid fiqh', 'qowaid fiqh'), ('fathul qorib', 'fathul qorib'), ('mantiq', 'mantiq'), ('nubzah', 'nubzah'), ('fathul muin', 'fathul muin'), ('balaghoh', 'balaghoh')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strarudl',
            name='predikat',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strbalaghoh',
            name='predikat',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strfaroid',
            name='predikat',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strmantiq',
            name='predikat',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strmuin',
            name='predikat',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strnubzah',
            name='predikat',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strqorib',
            name='predikat',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strqowaid',
            name='predikat',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strusul',
            name='predikat',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='takhossus',
            name='tkh',
            field=models.CharField(blank=True, choices=[('faroid', 'faroid'), ('fathul qorib', 'fathul qorib'), ('mantiq', 'mantiq'), ('nubzah', 'nubzah'), ('fathul muin', 'fathul muin'), ('qowaid', 'qowaid'), ('Arudl', 'Arudl'), ('usul', 'usul'), ('balaghoh', 'balaghoh')], max_length=30, null=True),
        ),
    ]
