# Generated by Django 3.1.3 on 2021-07-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstor', '0072_auto_20210704_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='santri',
            name='tanggal_lahir',
        ),
        migrations.RemoveField(
            model_name='santri',
            name='tempat_lahir',
        ),
        migrations.AlterField(
            model_name='juznubzah',
            name='juz',
            field=models.CharField(blank=True, choices=[('juz 2', 'juz 2'), ('juz 1', 'juz 1'), ('takmilah', 'takmilah'), ('juz 4', 'juz 4'), ('juz 3', 'juz 3'), ('juz 5', 'juz 5')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='jk',
            field=models.CharField(blank=True, choices=[('perempuan', 'perempuan'), ('laki-laki', 'laki-laki')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='marhalah',
            field=models.CharField(blank=True, choices=[('Tamhidiyah', 'Tamhidiyah'), ('Mahad Aly', 'Mahad Aly'), ('Idadiyah', 'Idadiyah')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='status',
            field=models.CharField(blank=True, choices=[('siswa', 'siswa'), ('salaf', 'salaf'), ('mahasiswa', 'mahasiswa')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='takhossus',
            field=models.CharField(blank=True, choices=[('balaghoh', 'balaghoh'), ('nubzah', 'nubzah'), ('qowaid fiqh', 'qowaid fiqh'), ('faroid', 'faroid'), ('fathul qorib', 'fathul qorib'), ('mantiq', 'mantiq'), ('fathul muin', 'fathul muin'), ('usul fiqh', 'usul fiqh'), ('arudl', 'arudl')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='takhossus',
            name='tkh',
            field=models.CharField(blank=True, choices=[('balaghoh', 'balaghoh'), ('nubzah', 'nubzah'), ('Arudl', 'Arudl'), ('faroid', 'faroid'), ('fathul qorib', 'fathul qorib'), ('usul', 'usul'), ('mantiq', 'mantiq'), ('fathul muin', 'fathul muin'), ('qowaid', 'qowaid')], max_length=30, null=True),
        ),
    ]
