# Generated by Django 3.1.3 on 2021-07-06 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appstor', '0073_auto_20210704_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juznubzah',
            name='juz',
            field=models.CharField(blank=True, choices=[('juz 1', 'juz 1'), ('juz 2', 'juz 2'), ('juz 4', 'juz 4'), ('juz 3', 'juz 3'), ('juz 5', 'juz 5'), ('takmilah', 'takmilah')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='marhalah',
            field=models.CharField(blank=True, choices=[('Tamhidiyah', 'Tamhidiyah'), ('Idadiyah', 'Idadiyah'), ('Mahad Aly', 'Mahad Aly')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='status',
            field=models.CharField(blank=True, choices=[('salaf', 'salaf'), ('mahasiswa', 'mahasiswa'), ('siswa', 'siswa')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='takhossus',
            field=models.CharField(blank=True, choices=[('faroid', 'faroid'), ('balaghoh', 'balaghoh'), ('qowaid fiqh', 'qowaid fiqh'), ('fathul qorib', 'fathul qorib'), ('nubzah', 'nubzah'), ('usul fiqh', 'usul fiqh'), ('fathul muin', 'fathul muin'), ('arudl', 'arudl'), ('mantiq', 'mantiq')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strarudl',
            name='predikat',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strbalaghoh',
            name='predikat',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strfaroid',
            name='predikat',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strmantiq',
            name='predikat',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strmuin',
            name='predikat',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strnubzah',
            name='predikat',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strqorib',
            name='predikat',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strqowaid',
            name='predikat',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strusul',
            name='predikat',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='takhossus',
            name='tkh',
            field=models.CharField(blank=True, choices=[('faroid', 'faroid'), ('balaghoh', 'balaghoh'), ('Arudl', 'Arudl'), ('fathul qorib', 'fathul qorib'), ('usul', 'usul'), ('nubzah', 'nubzah'), ('qowaid', 'qowaid'), ('fathul muin', 'fathul muin'), ('mantiq', 'mantiq')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Nubzah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nubzah', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appstor.halnubzah')),
            ],
        ),
    ]
