# Generated by Django 3.1.3 on 2021-07-06 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appstor', '0074_auto_20210706_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nubzah',
            name='nubzah',
        ),
        migrations.RemoveField(
            model_name='strnubzah',
            name='hal',
        ),
        migrations.RemoveField(
            model_name='strnubzah',
            name='juz',
        ),
        migrations.AddField(
            model_name='nubzah',
            name='juz',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='strnubzah',
            name='nubzah',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appstor.nubzah'),
        ),
        migrations.AlterField(
            model_name='santri',
            name='jk',
            field=models.CharField(blank=True, choices=[('laki-laki', 'laki-laki'), ('perempuan', 'perempuan')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='status',
            field=models.CharField(blank=True, choices=[('siswa', 'siswa'), ('mahasiswa', 'mahasiswa'), ('salaf', 'salaf')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='takhossus',
            field=models.CharField(blank=True, choices=[('fathul qorib', 'fathul qorib'), ('faroid', 'faroid'), ('balaghoh', 'balaghoh'), ('fathul muin', 'fathul muin'), ('qowaid fiqh', 'qowaid fiqh'), ('nubzah', 'nubzah'), ('usul fiqh', 'usul fiqh'), ('mantiq', 'mantiq'), ('arudl', 'arudl')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strarudl',
            name='predikat',
            field=models.CharField(blank=True, choices=[('C', 'C'), ('A', 'A'), ('B', 'B')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strbalaghoh',
            name='predikat',
            field=models.CharField(blank=True, choices=[('C', 'C'), ('A', 'A'), ('B', 'B')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strfaroid',
            name='predikat',
            field=models.CharField(blank=True, choices=[('C', 'C'), ('A', 'A'), ('B', 'B')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strmantiq',
            name='predikat',
            field=models.CharField(blank=True, choices=[('C', 'C'), ('A', 'A'), ('B', 'B')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strmuin',
            name='predikat',
            field=models.CharField(blank=True, choices=[('C', 'C'), ('A', 'A'), ('B', 'B')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strnubzah',
            name='predikat',
            field=models.CharField(blank=True, choices=[('C', 'C'), ('A', 'A'), ('B', 'B')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strqorib',
            name='predikat',
            field=models.CharField(blank=True, choices=[('C', 'C'), ('A', 'A'), ('B', 'B')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strqowaid',
            name='predikat',
            field=models.CharField(blank=True, choices=[('C', 'C'), ('A', 'A'), ('B', 'B')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strusul',
            name='predikat',
            field=models.CharField(blank=True, choices=[('C', 'C'), ('A', 'A'), ('B', 'B')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='takhossus',
            name='tkh',
            field=models.CharField(blank=True, choices=[('fathul qorib', 'fathul qorib'), ('faroid', 'faroid'), ('balaghoh', 'balaghoh'), ('fathul muin', 'fathul muin'), ('nubzah', 'nubzah'), ('qowaid', 'qowaid'), ('mantiq', 'mantiq'), ('usul', 'usul'), ('Arudl', 'Arudl')], max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='HalNubzah',
        ),
        migrations.DeleteModel(
            name='JuzNubzah',
        ),
    ]
