# Generated by Django 3.1.3 on 2021-07-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstor', '0079_auto_20210706_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nubzah',
            name='juz',
            field=models.CharField(blank=True, choices=[('juz 2', 'juz 2'), ('juz 4', 'juz 4'), ('juz 5', 'juz 5'), ('juz 1', 'juz 1'), ('juz 3', 'juz 3'), ('takmilah', 'takmilah')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='jk',
            field=models.CharField(blank=True, choices=[('perempuan', 'perempuan'), ('laki-laki', 'laki-laki')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='marhalah',
            field=models.CharField(blank=True, choices=[('Mahad Aly', 'Mahad Aly'), ('Tamhidiyah', 'Tamhidiyah'), ('Idadiyah', 'Idadiyah')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='status',
            field=models.CharField(blank=True, choices=[('salaf', 'salaf'), ('mahasiswa', 'mahasiswa'), ('siswa', 'siswa')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='takhossus',
            field=models.CharField(blank=True, choices=[('fathul qorib', 'fathul qorib'), ('arudl', 'arudl'), ('fathul muin', 'fathul muin'), ('nubzah', 'nubzah'), ('faroid', 'faroid'), ('usul fiqh', 'usul fiqh'), ('qowaid fiqh', 'qowaid fiqh'), ('mantiq', 'mantiq'), ('balaghoh', 'balaghoh')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='setoran',
            name='predikat',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('A', 'A'), ('C', 'C')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strarudl',
            name='predikat',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('A', 'A'), ('C', 'C')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strbalaghoh',
            name='predikat',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('A', 'A'), ('C', 'C')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strfaroid',
            name='predikat',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('A', 'A'), ('C', 'C')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strmantiq',
            name='predikat',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('A', 'A'), ('C', 'C')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strmuin',
            name='predikat',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('A', 'A'), ('C', 'C')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strnubzah',
            name='predikat',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('A', 'A'), ('C', 'C')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strqorib',
            name='predikat',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('A', 'A'), ('C', 'C')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strqowaid',
            name='predikat',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('A', 'A'), ('C', 'C')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strusul',
            name='predikat',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('A', 'A'), ('C', 'C')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='takhossus',
            name='tkh',
            field=models.CharField(blank=True, choices=[('fathul qorib', 'fathul qorib'), ('fathul muin', 'fathul muin'), ('Arudl', 'Arudl'), ('nubzah', 'nubzah'), ('faroid', 'faroid'), ('qowaid', 'qowaid'), ('mantiq', 'mantiq'), ('balaghoh', 'balaghoh'), ('usul', 'usul')], max_length=30, null=True),
        ),
    ]
