# Generated by Django 3.1.3 on 2021-07-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstor', '0081_auto_20210706_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asatidz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, null=True)),
                ('alamat', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, choices=[('siswa', 'siswa'), ('salaf', 'salaf'), ('mahasiswa', 'mahasiswa')], max_length=200, null=True)),
                ('jk', models.CharField(blank=True, choices=[('perempuan', 'perempuan'), ('laki-laki', 'laki-laki')], max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='nubzah',
            name='juz',
            field=models.CharField(blank=True, choices=[('juz 2', 'juz 2'), ('juz 4', 'juz 4'), ('takmilah', 'takmilah'), ('juz 1', 'juz 1'), ('juz 5', 'juz 5'), ('juz 3', 'juz 3')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='marhalah',
            field=models.CharField(blank=True, choices=[('Tamhidiyah', 'Tamhidiyah'), ('Mahad Aly', 'Mahad Aly'), ('Idadiyah', 'Idadiyah')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='status',
            field=models.CharField(blank=True, choices=[('siswa', 'siswa'), ('salaf', 'salaf'), ('mahasiswa', 'mahasiswa')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='takhossus',
            field=models.CharField(blank=True, choices=[('nubzah', 'nubzah'), ('qowaid fiqh', 'qowaid fiqh'), ('fathul qorib', 'fathul qorib'), ('balaghoh', 'balaghoh'), ('fathul muin', 'fathul muin'), ('usul fiqh', 'usul fiqh'), ('arudl', 'arudl'), ('faroid', 'faroid'), ('mantiq', 'mantiq')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='setoran',
            name='predikat',
            field=models.CharField(blank=True, choices=[('C', 'C'), ('B', 'B'), ('A', 'A')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strarudl',
            name='predikat',
            field=models.CharField(blank=True, choices=[('C', 'C'), ('B', 'B'), ('A', 'A')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strbalaghoh',
            name='predikat',
            field=models.CharField(blank=True, choices=[('C', 'C'), ('B', 'B'), ('A', 'A')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strfaroid',
            name='predikat',
            field=models.CharField(blank=True, choices=[('C', 'C'), ('B', 'B'), ('A', 'A')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strmantiq',
            name='predikat',
            field=models.CharField(blank=True, choices=[('C', 'C'), ('B', 'B'), ('A', 'A')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strmuin',
            name='predikat',
            field=models.CharField(blank=True, choices=[('C', 'C'), ('B', 'B'), ('A', 'A')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strnubzah',
            name='predikat',
            field=models.CharField(blank=True, choices=[('C', 'C'), ('B', 'B'), ('A', 'A')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strqorib',
            name='predikat',
            field=models.CharField(blank=True, choices=[('C', 'C'), ('B', 'B'), ('A', 'A')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strqowaid',
            name='predikat',
            field=models.CharField(blank=True, choices=[('C', 'C'), ('B', 'B'), ('A', 'A')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strusul',
            name='predikat',
            field=models.CharField(blank=True, choices=[('C', 'C'), ('B', 'B'), ('A', 'A')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='takhossus',
            name='tkh',
            field=models.CharField(blank=True, choices=[('nubzah', 'nubzah'), ('Arudl', 'Arudl'), ('fathul qorib', 'fathul qorib'), ('usul', 'usul'), ('qowaid', 'qowaid'), ('balaghoh', 'balaghoh'), ('fathul muin', 'fathul muin'), ('faroid', 'faroid'), ('mantiq', 'mantiq')], max_length=30, null=True),
        ),
    ]
