# Generated by Django 3.1.3 on 2021-07-09 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appstor', '0085_auto_20210709_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asatidz',
            name='jk',
            field=models.CharField(blank=True, choices=[('perempuan', 'perempuan'), ('laki-laki', 'laki-laki')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='asatidz',
            name='marhalah',
            field=models.CharField(blank=True, choices=[('Mahad Aly', 'Mahad Aly'), ('Idadiyah', 'Idadiyah'), ('Tamhidiyah', 'Tamhidiyah')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='asatidz',
            name='terima_setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appstor.setoran'),
        ),
        migrations.AlterField(
            model_name='nubzah',
            name='juz',
            field=models.CharField(blank=True, choices=[('juz 3', 'juz 3'), ('juz 1', 'juz 1'), ('takmilah', 'takmilah'), ('juz 4', 'juz 4'), ('juz 5', 'juz 5'), ('juz 2', 'juz 2')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='jk',
            field=models.CharField(blank=True, choices=[('perempuan', 'perempuan'), ('laki-laki', 'laki-laki')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='marhalah',
            field=models.CharField(blank=True, choices=[('Mahad Aly', 'Mahad Aly'), ('Idadiyah', 'Idadiyah'), ('Tamhidiyah', 'Tamhidiyah')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='takhossus',
            field=models.CharField(blank=True, choices=[('arudl', 'arudl'), ('faroid', 'faroid'), ('mantiq', 'mantiq'), ('qowaid fiqh', 'qowaid fiqh'), ('usul fiqh', 'usul fiqh'), ('balaghoh', 'balaghoh'), ('fathul muin', 'fathul muin'), ('fathul qorib', 'fathul qorib'), ('nubzah', 'nubzah')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='takhossus',
            name='tkh',
            field=models.CharField(blank=True, choices=[('usul', 'usul'), ('faroid', 'faroid'), ('mantiq', 'mantiq'), ('qowaid', 'qowaid'), ('balaghoh', 'balaghoh'), ('fathul muin', 'fathul muin'), ('Arudl', 'Arudl'), ('fathul qorib', 'fathul qorib'), ('nubzah', 'nubzah')], max_length=30, null=True),
        ),
    ]
