# Generated by Django 3.1.3 on 2021-07-12 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appstor', '0088_auto_20210710_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='asatidz',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asatidz',
            name='jk',
            field=models.CharField(blank=True, choices=[('perempuan', 'perempuan'), ('laki-laki', 'laki-laki')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='asatidz',
            name='marhalah',
            field=models.CharField(blank=True, choices=[('Idadiyah', 'Idadiyah'), ('Tamhidiyah', 'Tamhidiyah'), ('Mahad Aly', 'Mahad Aly')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='nubzah',
            name='juz',
            field=models.CharField(blank=True, choices=[('juz 4', 'juz 4'), ('takmilah', 'takmilah'), ('juz 1', 'juz 1'), ('juz 2', 'juz 2'), ('juz 3', 'juz 3'), ('juz 5', 'juz 5')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='jk',
            field=models.CharField(blank=True, choices=[('perempuan', 'perempuan'), ('laki-laki', 'laki-laki')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='marhalah',
            field=models.CharField(blank=True, choices=[('Idadiyah', 'Idadiyah'), ('Tamhidiyah', 'Tamhidiyah'), ('Mahad Aly', 'Mahad Aly')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='takhossus',
            field=models.CharField(blank=True, choices=[('nubzah', 'nubzah'), ('fathul muin', 'fathul muin'), ('qowaid fiqh', 'qowaid fiqh'), ('usul fiqh', 'usul fiqh'), ('mantiq', 'mantiq'), ('arudl', 'arudl'), ('balaghoh', 'balaghoh'), ('fathul qorib', 'fathul qorib'), ('faroid', 'faroid')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='setoran',
            name='predikat',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('A', 'A')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strarudl',
            name='predikat',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('A', 'A')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strbalaghoh',
            name='predikat',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('A', 'A')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strfaroid',
            name='predikat',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('A', 'A')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strmantiq',
            name='predikat',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('A', 'A')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strmuin',
            name='predikat',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('A', 'A')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strnubzah',
            name='predikat',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('A', 'A')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strqorib',
            name='predikat',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('A', 'A')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strqowaid',
            name='predikat',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('A', 'A')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='strusul',
            name='predikat',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('C', 'C'), ('A', 'A')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='takhossus',
            name='tkh',
            field=models.CharField(blank=True, choices=[('nubzah', 'nubzah'), ('fathul muin', 'fathul muin'), ('Arudl', 'Arudl'), ('mantiq', 'mantiq'), ('balaghoh', 'balaghoh'), ('fathul qorib', 'fathul qorib'), ('qowaid', 'qowaid'), ('usul', 'usul'), ('faroid', 'faroid')], max_length=30, null=True),
        ),
    ]
