# Generated by Django 3.2.5 on 2021-08-03 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appstor', '0095_auto_20210716_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marhalah', models.CharField(blank=True, choices=[('Mahad Aly', 'Mahad Aly'), ('Idadiyah', 'Idadiyah'), ('Tamhidiyah', 'Tamhidiyah')], max_length=30, null=True)),
                ('angkatan', models.CharField(blank=True, max_length=10, null=True)),
                ('takhossus', models.CharField(blank=True, max_length=200, null=True)),
                ('tanggal_masuk', models.DateTimeField(blank=True, max_length=200, null=True)),
                ('keterangan', models.CharField(blank=True, choices=[('Lulus', 'Lulus'), ('Tidak Lulus', 'Tidak Lulus'), ('belum Lulus', 'belum Lulus')], max_length=30, null=True)),
                ('lulus_tanggal', models.DateTimeField(blank=True, max_length=200, null=True)),
                ('naik_takhossus', models.CharField(blank=True, choices=[('Mahad Aly', 'Mahad Aly'), ('faroid', 'faroid'), ('balaghoh', 'balaghoh'), ('mantiq', 'mantiq'), ('Tamhidiyah', 'Tamhidiyah'), ('Idadiyah', 'Idadiyah'), ('nubzah', 'nubzah'), ('arudl', 'arudl'), ('fathul qorib', 'fathul qorib'), ('fathul muin', 'fathul muin'), ('qowaid fiqh', 'qowaid fiqh'), ('usul fiqh', 'usul fiqh')], max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='qorib',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='strarudl',
            name='halaman',
        ),
        migrations.RemoveField(
            model_name='strarudl',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='strbalaghoh',
            name='halaman',
        ),
        migrations.RemoveField(
            model_name='strbalaghoh',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='strfaroid',
            name='halaman',
        ),
        migrations.RemoveField(
            model_name='strfaroid',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='strmantiq',
            name='halaman',
        ),
        migrations.RemoveField(
            model_name='strmantiq',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='strmuin',
            name='halaman',
        ),
        migrations.RemoveField(
            model_name='strmuin',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='strnubzah',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='strnubzah',
            name='nubzah',
        ),
        migrations.RemoveField(
            model_name='strqorib',
            name='halaman',
        ),
        migrations.RemoveField(
            model_name='strqorib',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='strqowaid',
            name='halaman',
        ),
        migrations.RemoveField(
            model_name='strqowaid',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='strusul',
            name='halaman',
        ),
        migrations.RemoveField(
            model_name='strusul',
            name='nama',
        ),
        migrations.AlterField(
            model_name='asatidz',
            name='jk',
            field=models.CharField(blank=True, choices=[('perempuan', 'perempuan'), ('laki-laki', 'laki-laki')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='asatidz',
            name='marhalah',
            field=models.CharField(blank=True, choices=[('Mahad Aly', 'Mahad Aly'), ('Idadiyah', 'Idadiyah'), ('Tamhidiyah', 'Tamhidiyah')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='asatidz',
            name='status',
            field=models.CharField(blank=True, choices=[('siswa', 'siswa'), ('mahasiswa', 'mahasiswa'), ('salaf', 'salaf')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='nubzah',
            name='juz',
            field=models.CharField(blank=True, choices=[('juz 4', 'juz 4'), ('juz 5', 'juz 5'), ('juz 3', 'juz 3'), ('juz 1', 'juz 1'), ('takmilah', 'takmilah'), ('juz 2', 'juz 2')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='jk',
            field=models.CharField(blank=True, choices=[('perempuan', 'perempuan'), ('laki-laki', 'laki-laki')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='marhalah',
            field=models.CharField(blank=True, choices=[('Mahad Aly', 'Mahad Aly'), ('Idadiyah', 'Idadiyah'), ('Tamhidiyah', 'Tamhidiyah')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='status',
            field=models.CharField(blank=True, choices=[('siswa', 'siswa'), ('mahasiswa', 'mahasiswa'), ('salaf', 'salaf')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='takhossus',
            field=models.CharField(blank=True, choices=[('faroid', 'faroid'), ('balaghoh', 'balaghoh'), ('mantiq', 'mantiq'), ('nubzah', 'nubzah'), ('arudl', 'arudl'), ('fathul qorib', 'fathul qorib'), ('fathul muin', 'fathul muin'), ('qowaid fiqh', 'qowaid fiqh'), ('usul fiqh', 'usul fiqh')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='setoran',
            name='predikat',
            field=models.CharField(blank=True, choices=[('C', 'C'), ('A', 'A'), ('B', 'B')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='takhossus',
            name='tkh',
            field=models.CharField(blank=True, choices=[('balaghoh', 'balaghoh'), ('faroid', 'faroid'), ('mantiq', 'mantiq'), ('nubzah', 'nubzah'), ('Arudl', 'Arudl'), ('usul', 'usul'), ('qowaid', 'qowaid'), ('fathul qorib', 'fathul qorib'), ('fathul muin', 'fathul muin')], max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Arudl',
        ),
        migrations.DeleteModel(
            name='Balaghoh',
        ),
        migrations.DeleteModel(
            name='Faroid',
        ),
        migrations.DeleteModel(
            name='Mantiq',
        ),
        migrations.DeleteModel(
            name='Muin',
        ),
        migrations.DeleteModel(
            name='Qorib',
        ),
        migrations.DeleteModel(
            name='Qowaid',
        ),
        migrations.DeleteModel(
            name='strArudl',
        ),
        migrations.DeleteModel(
            name='strBalaghoh',
        ),
        migrations.DeleteModel(
            name='strFaroid',
        ),
        migrations.DeleteModel(
            name='strMantiq',
        ),
        migrations.DeleteModel(
            name='strMuin',
        ),
        migrations.DeleteModel(
            name='strNubzah',
        ),
        migrations.DeleteModel(
            name='strQorib',
        ),
        migrations.DeleteModel(
            name='strQowaid',
        ),
        migrations.DeleteModel(
            name='strUsul',
        ),
        migrations.DeleteModel(
            name='Usul',
        ),
        migrations.AddField(
            model_name='ket',
            name='nama',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appstor.santri'),
        ),
    ]
