# Generated by Django 3.2.5 on 2021-08-03 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstor', '0096_auto_20210804_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asatidz',
            name='jk',
            field=models.CharField(blank=True, choices=[('laki-laki', 'laki-laki'), ('perempuan', 'perempuan')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='asatidz',
            name='marhalah',
            field=models.CharField(blank=True, choices=[('Idadiyah', 'Idadiyah'), ('Mahad Aly', 'Mahad Aly'), ('Tamhidiyah', 'Tamhidiyah')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ket',
            name='keterangan',
            field=models.CharField(blank=True, choices=[('Tidak Lulus', 'Tidak Lulus'), ('Lulus', 'Lulus'), ('belum Lulus', 'belum Lulus')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ket',
            name='lulus_tanggal',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ket',
            name='marhalah',
            field=models.CharField(blank=True, choices=[('Idadiyah', 'Idadiyah'), ('Mahad Aly', 'Mahad Aly'), ('Tamhidiyah', 'Tamhidiyah')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ket',
            name='naik_takhossus',
            field=models.CharField(blank=True, choices=[('Idadiyah', 'Idadiyah'), ('nubzah', 'nubzah'), ('fathul qorib', 'fathul qorib'), ('faroid', 'faroid'), ('usul fiqh', 'usul fiqh'), ('arudl', 'arudl'), ('fathul muin', 'fathul muin'), ('qowaid fiqh', 'qowaid fiqh'), ('mantiq', 'mantiq'), ('Mahad Aly', 'Mahad Aly'), ('Tamhidiyah', 'Tamhidiyah'), ('balaghoh', 'balaghoh')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ket',
            name='takhossus',
            field=models.CharField(blank=True, choices=[('Idadiyah', 'Idadiyah'), ('nubzah', 'nubzah'), ('fathul qorib', 'fathul qorib'), ('faroid', 'faroid'), ('usul fiqh', 'usul fiqh'), ('arudl', 'arudl'), ('fathul muin', 'fathul muin'), ('qowaid fiqh', 'qowaid fiqh'), ('mantiq', 'mantiq'), ('Mahad Aly', 'Mahad Aly'), ('Tamhidiyah', 'Tamhidiyah'), ('balaghoh', 'balaghoh')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ket',
            name='tanggal_masuk',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='nubzah',
            name='juz',
            field=models.CharField(blank=True, choices=[('takmilah', 'takmilah'), ('juz 2', 'juz 2'), ('juz 4', 'juz 4'), ('juz 5', 'juz 5'), ('juz 3', 'juz 3'), ('juz 1', 'juz 1')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='jk',
            field=models.CharField(blank=True, choices=[('laki-laki', 'laki-laki'), ('perempuan', 'perempuan')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='marhalah',
            field=models.CharField(blank=True, choices=[('Idadiyah', 'Idadiyah'), ('Mahad Aly', 'Mahad Aly'), ('Tamhidiyah', 'Tamhidiyah')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='santri',
            name='takhossus',
            field=models.CharField(blank=True, choices=[('nubzah', 'nubzah'), ('fathul qorib', 'fathul qorib'), ('faroid', 'faroid'), ('usul fiqh', 'usul fiqh'), ('arudl', 'arudl'), ('fathul muin', 'fathul muin'), ('qowaid fiqh', 'qowaid fiqh'), ('mantiq', 'mantiq'), ('balaghoh', 'balaghoh')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='setoran',
            name='predikat',
            field=models.CharField(blank=True, choices=[('C', 'C'), ('B', 'B'), ('A', 'A')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='takhossus',
            name='tkh',
            field=models.CharField(blank=True, choices=[('nubzah', 'nubzah'), ('fathul qorib', 'fathul qorib'), ('usul', 'usul'), ('faroid', 'faroid'), ('Arudl', 'Arudl'), ('fathul muin', 'fathul muin'), ('qowaid', 'qowaid'), ('mantiq', 'mantiq'), ('balaghoh', 'balaghoh')], max_length=30, null=True),
        ),
    ]
